name: RunTests

on:
  push:
   branches: 
    - main

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
     - name: cd
       run: cd ..
     - name: Start
       run: echo $(ls)
     - name: test
       run: python3 TZ_3/test.py
